{
  "analyticsID": "",
  "report":
    {
      "bucketName": "",
      "fileName": "popularlist.json",
      "filter": ["^\/story\/|^\/projects\/"],
      "fileHostDomainRule":
        {
          "https://storage.googleapis.com/mirrormedia-files": "https://www.mirrormedia.mg",
          "https://storage.googleapis.com/static-mnews-tw-dev": "https://dev.mnews.tw",
          "https://storage.googleapis.com/mirror-tv-file": "https://dev.mnews.tw",
        },
      "pageSize": 20,
    },
  "slugBlacklist":
    [
      "aboutus",
      "ad-sales",
      "biography",
      "complaint",
      "faq",
      "press-self-regulation",
      "privacy",
      "standards",
      "webauthorization",
    ],
}
