---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-feed
  namespace: cron
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: feed-google-news-rss
  namespace: cron
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: ksa-feed
          containers:
            - name: mirror-tv-feed-google-news-rss
              image: gcr.io/mirror-tv-275709/mirror-tv-feed:20210203-1
              workingDir: /cronjobs/mirror-tv
              command: ["./start.sh"]
              args:
                - $(EXECFOLDER)
                - $(EXECSCRIPT)
              env:
                - name: EXECFOLDER
                  value: ./feed/google_news_rss
                - name: EXECSCRIPT
                  value: generate_google_news_rss.py
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: feed-line-today-xml
  namespace: cron
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        spec:
          serviceAccountName: ksa-feed
          containers:
            - name: mirror-tv-feed-line-today-xml
              image: gcr.io/mirror-tv-275709/mirror-tv-feed:20210203-1
              workingDir: /cronjobs/mirror-tv
              command: ["./start.sh"]
              args:
                - $(EXECFOLDER)
                - $(EXECSCRIPT)
              env:
                - name: EXECFOLDER
                  value: ./feed/line_today_xml
                - name: EXECSCRIPT
                  value: generate_line_today_xml.py
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: feed-yahoo-rss
  namespace: cron
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        spec:
          serviceAccountName: ksa-feed
          containers:
            - name: mirror-tv-feed-yahoo-rss
              image: gcr.io/mirror-tv-275709/mirror-tv-feed:20210203-1
              workingDir: /cronjobs/mirror-tv
              command: ["./start.sh"]
              args:
                - $(EXECFOLDER)
                - $(EXECSCRIPT)
              env:
                - name: EXECFOLDER
                  value: ./feed/yahoo_rss
                - name: EXECSCRIPT
                  value: generate_yahoo_rss.py
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          restartPolicy: OnFailure
